# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: multisend.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='multisend.proto',
  package='proto',
  syntax='proto3',
  serialized_pb=_b('\n\x0fmultisend.proto\x12\x05proto\"\'\n\x04Path\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x11\n\trecursive\x18\x02 \x01(\x08\"t\n\x06Status\x12\n\n\x02id\x18\x05 \x01(\x05\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x14\n\x0c\x62ind_address\x18\x02 \x01(\t\x12\x11\n\tbind_port\x18\x04 \x01(\x05\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x12\n\nextra_info\x18\x08 \x01(\t\"f\n\rReceiverReply\x12\x0f\n\x07peer_id\x18\x01 \x01(\x05\x12\x14\n\x0c\x62ind_address\x18\x02 \x01(\t\x12\x11\n\tbind_port\x18\x03 \x01(\x05\x12\x1b\n\x05\x65rror\x18\x08 \x01(\x0b\x32\x0c.proto.Error\")\n\x05\x45rror\x12\x0f\n\x07peer_id\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"4\n\x0cReceiverList\x12$\n\treceivers\x18\x02 \x03(\x0b\x32\x11.proto.Parameters\"\xd2\x01\n\nParameters\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06socket\x18\x02 \x01(\x08\x12\x13\n\x0b\x62uffer_size\x18\x05 \x01(\x04\x12\x0c\n\x04port\x18\r \x01(\x05\x12\x14\n\x0c\x62ind_address\x18\x15 \x01(\t\x12\x14\n\x0crcvr_address\x18\x16 \x01(\t\x12\x14\n\x0csndr_address\x18\x17 \x01(\t\x12\x0c\n\x04list\x18\x18 \x03(\t\x12\x17\n\x03ssh\x18\x19 \x01(\x0b\x32\n.proto.Ssh\x12\x1c\n\x04\x61rgs\x18\x1a \x01(\x0b\x32\x0e.proto.AppOpts\"<\n\x03Ssh\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x0b\n\x03pwd\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\"F\n\x07\x41ppOpts\x12\x0c\n\x04port\x18\x01 \x01(\r\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x10\n\x08\x62in_path\x18\x06 \x01(\t\x12\n\n\x02\x64\x66\x18\x07 \x01(\t\"\x06\n\x04Void2\xcb\x01\n\x03\x41pi\x12\x31\n\x0bStartSender\x12\x11.proto.Parameters\x1a\r.proto.Status\"\x00\x12*\n\x08SendFile\x12\x0b.proto.Path\x1a\r.proto.Status\"\x00\x30\x01\x12=\n\x0c\x41\x64\x64Receivers\x12\x13.proto.ReceiverList\x1a\x14.proto.ReceiverReply\"\x00\x30\x01\x12&\n\x08Shutdown\x12\x0b.proto.Void\x1a\x0b.proto.Void\"\x00\x62\x06proto3')
)




_PATH = _descriptor.Descriptor(
  name='Path',
  full_name='proto.Path',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='proto.Path.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recursive', full_name='proto.Path.recursive', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=65,
)


_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='proto.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.Status.id', index=0,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ok', full_name='proto.Status.ok', index=1,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bind_address', full_name='proto.Status.bind_address', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bind_port', full_name='proto.Status.bind_port', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='proto.Status.error_message', index=4,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='extra_info', full_name='proto.Status.extra_info', index=5,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=183,
)


_RECEIVERREPLY = _descriptor.Descriptor(
  name='ReceiverReply',
  full_name='proto.ReceiverReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='peer_id', full_name='proto.ReceiverReply.peer_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bind_address', full_name='proto.ReceiverReply.bind_address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bind_port', full_name='proto.ReceiverReply.bind_port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='proto.ReceiverReply.error', index=3,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=287,
)


_ERROR = _descriptor.Descriptor(
  name='Error',
  full_name='proto.Error',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='peer_id', full_name='proto.Error.peer_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='proto.Error.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=330,
)


_RECEIVERLIST = _descriptor.Descriptor(
  name='ReceiverList',
  full_name='proto.ReceiverList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='receivers', full_name='proto.ReceiverList.receivers', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=332,
  serialized_end=384,
)


_PARAMETERS = _descriptor.Descriptor(
  name='Parameters',
  full_name='proto.Parameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.Parameters.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='socket', full_name='proto.Parameters.socket', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='buffer_size', full_name='proto.Parameters.buffer_size', index=2,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='proto.Parameters.port', index=3,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bind_address', full_name='proto.Parameters.bind_address', index=4,
      number=21, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rcvr_address', full_name='proto.Parameters.rcvr_address', index=5,
      number=22, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sndr_address', full_name='proto.Parameters.sndr_address', index=6,
      number=23, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='list', full_name='proto.Parameters.list', index=7,
      number=24, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ssh', full_name='proto.Parameters.ssh', index=8,
      number=25, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='args', full_name='proto.Parameters.args', index=9,
      number=26, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=597,
)


_SSH = _descriptor.Descriptor(
  name='Ssh',
  full_name='proto.Ssh',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='proto.Ssh.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='proto.Ssh.user', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pwd', full_name='proto.Ssh.pwd', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='proto.Ssh.port', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=599,
  serialized_end=659,
)


_APPOPTS = _descriptor.Descriptor(
  name='AppOpts',
  full_name='proto.AppOpts',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='port', full_name='proto.AppOpts.port', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='proto.AppOpts.address', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bin_path', full_name='proto.AppOpts.bin_path', index=2,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='df', full_name='proto.AppOpts.df', index=3,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=661,
  serialized_end=731,
)


_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='proto.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=733,
  serialized_end=739,
)

_RECEIVERREPLY.fields_by_name['error'].message_type = _ERROR
_RECEIVERLIST.fields_by_name['receivers'].message_type = _PARAMETERS
_PARAMETERS.fields_by_name['ssh'].message_type = _SSH
_PARAMETERS.fields_by_name['args'].message_type = _APPOPTS
DESCRIPTOR.message_types_by_name['Path'] = _PATH
DESCRIPTOR.message_types_by_name['Status'] = _STATUS
DESCRIPTOR.message_types_by_name['ReceiverReply'] = _RECEIVERREPLY
DESCRIPTOR.message_types_by_name['Error'] = _ERROR
DESCRIPTOR.message_types_by_name['ReceiverList'] = _RECEIVERLIST
DESCRIPTOR.message_types_by_name['Parameters'] = _PARAMETERS
DESCRIPTOR.message_types_by_name['Ssh'] = _SSH
DESCRIPTOR.message_types_by_name['AppOpts'] = _APPOPTS
DESCRIPTOR.message_types_by_name['Void'] = _VOID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Path = _reflection.GeneratedProtocolMessageType('Path', (_message.Message,), dict(
  DESCRIPTOR = _PATH,
  __module__ = 'multisend_pb2'
  # @@protoc_insertion_point(class_scope:proto.Path)
  ))
_sym_db.RegisterMessage(Path)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'multisend_pb2'
  # @@protoc_insertion_point(class_scope:proto.Status)
  ))
_sym_db.RegisterMessage(Status)

ReceiverReply = _reflection.GeneratedProtocolMessageType('ReceiverReply', (_message.Message,), dict(
  DESCRIPTOR = _RECEIVERREPLY,
  __module__ = 'multisend_pb2'
  # @@protoc_insertion_point(class_scope:proto.ReceiverReply)
  ))
_sym_db.RegisterMessage(ReceiverReply)

Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), dict(
  DESCRIPTOR = _ERROR,
  __module__ = 'multisend_pb2'
  # @@protoc_insertion_point(class_scope:proto.Error)
  ))
_sym_db.RegisterMessage(Error)

ReceiverList = _reflection.GeneratedProtocolMessageType('ReceiverList', (_message.Message,), dict(
  DESCRIPTOR = _RECEIVERLIST,
  __module__ = 'multisend_pb2'
  # @@protoc_insertion_point(class_scope:proto.ReceiverList)
  ))
_sym_db.RegisterMessage(ReceiverList)

Parameters = _reflection.GeneratedProtocolMessageType('Parameters', (_message.Message,), dict(
  DESCRIPTOR = _PARAMETERS,
  __module__ = 'multisend_pb2'
  # @@protoc_insertion_point(class_scope:proto.Parameters)
  ))
_sym_db.RegisterMessage(Parameters)

Ssh = _reflection.GeneratedProtocolMessageType('Ssh', (_message.Message,), dict(
  DESCRIPTOR = _SSH,
  __module__ = 'multisend_pb2'
  # @@protoc_insertion_point(class_scope:proto.Ssh)
  ))
_sym_db.RegisterMessage(Ssh)

AppOpts = _reflection.GeneratedProtocolMessageType('AppOpts', (_message.Message,), dict(
  DESCRIPTOR = _APPOPTS,
  __module__ = 'multisend_pb2'
  # @@protoc_insertion_point(class_scope:proto.AppOpts)
  ))
_sym_db.RegisterMessage(AppOpts)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'multisend_pb2'
  # @@protoc_insertion_point(class_scope:proto.Void)
  ))
_sym_db.RegisterMessage(Void)



_API = _descriptor.ServiceDescriptor(
  name='Api',
  full_name='proto.Api',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=742,
  serialized_end=945,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartSender',
    full_name='proto.Api.StartSender',
    index=0,
    containing_service=None,
    input_type=_PARAMETERS,
    output_type=_STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendFile',
    full_name='proto.Api.SendFile',
    index=1,
    containing_service=None,
    input_type=_PATH,
    output_type=_STATUS,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddReceivers',
    full_name='proto.Api.AddReceivers',
    index=2,
    containing_service=None,
    input_type=_RECEIVERLIST,
    output_type=_RECEIVERREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Shutdown',
    full_name='proto.Api.Shutdown',
    index=3,
    containing_service=None,
    input_type=_VOID,
    output_type=_VOID,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_API)

DESCRIPTOR.services_by_name['Api'] = _API

# @@protoc_insertion_point(module_scope)
